-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Tempo de geração: 26-Nov-2025 às 18:35
-- Versão do servidor: 5.6.51
-- versão do PHP: 8.0.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `loja`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `produtos`
--

CREATE TABLE `produtos` (
  `id` int(11) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `marca` varchar(20) NOT NULL,
  `imagem` varchar(100) NOT NULL DEFAULT 'no-image.jpg',
  `categoria` varchar(50) NOT NULL,
  `descricao` text NOT NULL,
  `valor` decimal(7,2) NOT NULL,
  `disponibilidade` tinyint(1) NOT NULL,
  `data_criado` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_editado` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `produtos`
--

INSERT INTO `produtos` (`id`, `nome`, `marca`, `imagem`, `categoria`, `descricao`, `valor`, `disponibilidade`, `data_criado`, `data_editado`) VALUES
(1, 'iPhone 16 Pro Max (512 GB) – Titânio preto', 'Apple', 'iphone.jpg', 'Celulares', 'iPhone 16. Novo Controle da Câmera, câmera Fusion de 48 MP, cinco cores lindas e o chip A18. A duração da bateria varia de acordo com o uso e a configuração. Consulte apple.com/br/batteries para obter mais informações. Acessórios vendidos separadamente. As telas têm bordas arredondadas. Quando medida como um retângulo, a tela tem 6,12 polegadas (iPhone 16), 6,69 polegadas (iPhone 16 Plus), 6,27 polegadas (iPhone 16 Pro) ou 6,86 polegadas (iPhone 16 Pro Max) na diagonal. A área real de visualização é menor. Alguns recursos podem não estar disponíveis em todos os países ou regiões. O iPhone 16 e o iPhone 16 Pro são capazes de identificar um acidente grave de carro e ligar para os serviços de emergência. Requer uma conexão de rede celular ou chamadas Wi-Fi.\r\n\r\nFicha Técnica:\r\nArmazenamento interno de 128GB\r\nTela de 6,1\" polegadas\r\nCâmera traseira de 48 MP\r\nCâmera frontal de 12MP', '9179.10', 1, '2025-11-13 18:58:44', '2025-11-14 18:11:40'),
(2, 'Galaxy S24 FE Enterprise Edition 256GB 5G 8GB RAM Grafite 6,7\" Câm. Tripla + Selfie 10MP', 'Samsung', 'galaxys4fe.jpg', 'Celulares', 'O Galaxy S24 FE Enterprise Edition Grafite 5G é o smartphone da Samsung com design elegante e robusto, com acabamento em alumínio e proteção Corning Gorilla Victus. Ele possui uma tela Dynamic Amoled 2X de 6,7\" com resolução FHD+ (1080x2340), processador Samsung Exynos 2400e Deca-Core de 3.1GHz, 8GB de memória RAM e 256GB de armazenamento interno expansível. A câmera traseira tripla conta com sensores de 50MP (Wide) + 12MP (Ultra Wide) + 8MP (Telefoto), enquanto a câmera frontal possui 10MP. A bateria de 4700mAh tem autonomia para o dia todo, com suporte para carregamento rápido de 25W. Tem garantia de 7 atualizações de sistema operacional e 7 anos de atualizações de segurança. Ele também conta com recursos exclusivos da Samsung, como o Galaxy AI (Inteligência Artificial), o Cadeado Galaxy e o Knox, que protegem seus dados e privacidade. O Samsung Galaxy S24 FE Enterprise Edition Grafite 5G é o smartphone ideal para quem busca um aparelho poderoso, com design elegante e robusto, e recursos avançados de segurança. Atenção: Produto não acompanha fone de ouvido.\r\n\r\nFicha Técnica:\r\nArmazenamento Interno de 256GB\r\nMemória RAM de 8GB\r\nTela de 6,7\"\r\nCâmera traseira tripla de 50MP + 12MP + 8MP\r\nCâmera frontal de 10MP\r\nBateria de 4700mAh', '2799.89', 1, '2025-11-13 19:13:33', '2025-11-14 18:16:50'),
(3, 'PlayStation 5 Slim Edição Digital 1TB 2 Controles Branco ', 'Sony', 'play5.jpg', 'Eletrônicos', 'Confira o PlayStation Slim Edição Digital 2025 da Sony. A evolução do entretenimento em suas mãos. Este console redefine a experiência de jogo com um design elegante na cor branca e um poderoso SSD de 1TB, garantindo velocidade e espaço de sobra para seus títulos favoritos. Acompanhando o futuro dos games, inclui um controle sem fio. E para começar sua jornada com o pé direito, acompanha jogos incríveis: 1 Voucher para o jogo completo do Gran Turismo 7, 1 Voucher para o jogo completo do Astro Bot e Jogo Astro’s Playroom (jogo pré-instalado). Prepare-se para gráficos deslumbrantes, carregamentos ultrarrápidos e uma imersão sem igual. O PS5 Slim Edição Digital é a sua porta de entrada para um universo de aventuras digitais. Atenção: É necessário ter uma conta na PlayStation Store e conexão à Internet para resgatar o voucher.\r\n\r\nFicha Técnica\r\nReferência: CFI-2014B01X\r\nModelo: PS5 Slim Edição Digital\r\nAno de Lançamento: 2025\r\nTipo de Armazenamento: SSD\r\nCapacidade do Armazenamento: 1TB\r\nQuantidade de Controles: 2 controles\r\nTipo de Controle: Sem fio', '3571.05', 1, '2025-11-13 19:16:37', '2025-11-14 18:18:36'),
(4, 'Notebook Gamer Acer Nitro V15 Intel Core i5 512GB SSD 16GB RAM 15,6\" Full HD', 'Acer', 'nitroV15.jpg', 'Informática', 'O notebook gamer Acer Nitro V15 ANV15-51-582R é perfeito para quem busca um equipamento potente e com ótimo custo-benefício. Ele conta com processador Intel Core i5 13420H de 13ª geração, 512GB de armazenamento SSD, 16GB de memória RAM, tela LED de 15,6\" com resolução Full HD (1920x1080) e frequência de 144Hz, painel IPS e placa de vídeo dedicada NVIDIA GeForce RTX 3050 com 6GB de memória. O sistema operacional é o Linux Gutta. Com esse conjunto de hardware, ele é capaz de rodar os games mais atuais com ótima qualidade de imagem e fluidez. Além disso, ele também é uma ótima opção para quem trabalha com edição de vídeo, fotos ou outros programas que exigem um alto desempenho. Ainda conta com bateria de longa duração, que permite você usá-lo por até 7 horas sem precisar se preocupar com o carregamento. Além disso, ele também possui um sistema de resfriamento eficiente, que evita que o notebook fique muito quente durante o uso. Este modelo possuí capacidade para a instalação (upgrades) de SSDs NVMe: Slot dedicado ocupado M.2 2280, compatível com barramento PCIe 4.0 x4 NVMe de até 1TB. (Não acompanha o produto). Slot dedicado livre M.2 2280, compatível com barramento PCIe 3.0 x4 NVMe de até 1TB. (Não acompanha o produto).\r\n\r\nFicha Técnica:\r\nProcessador Intel Core i5\r\n16GB de memória RAM\r\n512GB de SSD\r\nPlaca de vídeo NVIDIA RTX 3050\r\nTela de 15,6 polegadas', '4843.33', 1, '2025-11-13 19:19:48', '2025-11-14 18:19:52'),
(5, 'Notebook Dell Inspiron 15 I15-I3100-A15P Intel Core 3 8GB RAM 512GB SSD 15,6\" Full HD Windows 11', 'Dell', 'inspiron15.avif', 'Informática', 'O notebook Dell Inspiron 15 I15-I3100-A15P proporciona uma forma inteligente de aproveitar seu dia. Ele é tão elegante por fora quanto eficiente por dentro. Contando com processador Intel Core 3-100U, 8GB de memória RAM e 512GB de SSD, você pode concluir sua lista de tarefas num piscar de olhos. Conecte-se a tudo de que você gosta. Curta chats de vídeo de qualidade com uma webcam HD integrada que mostra você da melhor forma. Passe mais tempo diante da tela com o software Dell ComfortView, uma solução de software que ajuda a reduzir as emissões nocivas de luz azul para manter os olhos confortáveis durante longos tempos de visualização. A tela é de 15,6\" com resolução Full HD (1920x1080) e o sistema operacional é o Windows 11 para uma experiência completa e Microsoft Office Trial – Versão para experimentação, válida por 30 dias.\r\n\r\nFicha Técnica:\r\nProcessador Intel Core 3-100U\r\nMemória RAM de 8GB\r\nSSD de 512GB\r\nTela de 15,6 polegadas\r\nSistema operacional Windows 11', '2943.33', 1, '2025-11-13 19:22:38', '2025-11-14 18:21:00'),
(6, 'Google Pixel 9 Pro 256GB - Obsidian', 'Google', 'pixel9.jpg', 'Celulares', 'O mais novo Pixel Pro com IA avançada, entregando uma experiência fotográfica inigualável e recursos de IA generativa. Possui chip Tensor G4 e 7 anos de atualizações de sistema garantidos. Ficha Técnica: Armazenamento: 256GB. Tela: Super Actua 6.7\". Câmera: Tripla de 50MP. Processador: Google Tensor G4.', '7999.00', 1, '2025-11-13 19:34:38', '2025-11-14 18:24:29'),
(7, 'Google Pixel 9 128GB - Mint', 'Google', 'pixel9mint.webp', 'Celulares', 'O poder do Google AI em um formato compacto e acessível. O Pixel 9 traz o mesmo processador Tensor G4 e recursos de câmera mágicos de seu irmão maior. Ficha Técnica: Armazenamento: 128GB. Tela: Actua 6.2\". Câmera: Dupla. Processador: Google Tensor G4.', '6499.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:26:01'),
(8, 'Xiaomi 15 Pro 512GB - Titanium Gray', 'Xiaomi', 'xiaomi15pro.webp', 'Celulares', 'O flagship da Xiaomi com co-engenharia Leica. Foco total em performance e captura de imagem, com um sensor principal massivo de 1 polegada e o carregamento mais rápido do mercado. Ficha Técnica: Armazenamento: 512GB. Câmera: Principal Leica de 1 polegada. Processador: Snapdragon 8 Gen 4. Carregamento: HyperCharge de 120W.', '7899.90', 1, '2025-11-13 19:36:18', '2025-11-14 18:27:22'),
(9, 'Xiaomi Redmi Note 14 Pro 256GB - Black', 'Xiaomi', 'redmi14.webp', 'Celulares', 'O rei do custo-benefício em nível premium. O Redmi Note 14 Pro oferece uma câmera de alta resolução e uma tela fluida, ideal para quem quer muito sem gastar o valor de um flagship. Ficha Técnica: Armazenamento: 256GB. Câmera: 200MP. Tela: 1.5K de 120Hz. Bateria: 5000mAh.', '2499.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:28:12'),
(10, 'Motorola Edge 60 Pro 256GB - Vegan Leather Blue', 'Motorola', 'edge60.jpg', 'Celulares', 'Experiência premium com design sofisticado em couro vegano. Sua tela pOLED de 144Hz é perfeita para jogos, e a câmera com estabilização gimbal captura vídeos incrivelmente estáveis. Ficha Técnica: Armazenamento: 256GB. Tela: pOLED 6.7\" 144Hz. Processador: Snapdragon 8 Gen 3. Câmera: 50MP com estabilização gimbal.', '5999.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:31:02'),
(11, 'Motorola Moto G95 128GB - Grafite', 'Motorola', 'motog95.jpg', 'Celulares', 'O favorito da linha G, agora com uma bateria de longa duração e câmera de 108MP. O Moto G95 é sinônimo de confiabilidade para o dia a dia. Ficha Técnica: Armazenamento: 128GB. Câmera: 108MP. Bateria: 6000mAh. Carregamento: Rápido de 33W.', '1899.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:34:00'),
(12, 'Google Pixel 8a 128GB - Bay (Blue)', 'Google', 'pixel8a.jpg', 'Celulares', 'A forma mais acessível de ter a IA do Google e a melhor câmera de smartphone em sua classe. O Pixel 8a traz o chip Tensor G3 e recursos mágicos de edição de fotos. Ficha Técnica: Armazenamento: 128GB. Câmera: 64MP com recursos de IA. Processador: Google Tensor G3. Tela: Actua Display 120Hz.', '3999.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:36:05'),
(13, 'Xiaomi Poco F7 Pro 512GB - Yellow', 'Xiaomi', 'pocof7pro.webp', 'Celulares', 'O verdadeiro \'Flagship Killer\' focado em performance bruta para jogos. Combina o Snapdragon 8 Gen 3 com um sistema de refrigeração líquida avançado para longas sessões de gameplay. Ficha Técnica: Armazenamento: 512GB. Processador: Snapdragon 8 Gen 3. Refrigeração: Líquida (LiquidCool 4.0). Tela: AMOLED 144Hz.', '4200.00', 1, '2025-11-13 19:36:18', '2025-11-14 18:36:59'),
(14, 'Sony BRAVIA 9 65\" Mini LED 4K Google TV', 'Sony', 'bravia65.jpg', 'Eletrônicos', 'A TV Mini LED top de linha da Sony, com a tecnologia XR Backlight Master Drive que oferece o contraste mais preciso e brilho intenso. Perfeita para filmes e para o PlayStation 5. Ficha Técnica: Tamanho: 65 polegadas. Painel: Mini LED. Resolução: 4K UHD. Sistema: Google TV. Som: Acoustic Multi-Audio+.', '10999.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:39:13'),
(15, 'Headphone Sony WH-1000XM6 com Cancelamento de Ruído', 'Sony', 'phone-sony.jpg', 'Eletrônicos', 'A nova geração do melhor cancelamento de ruído do mercado. O XM6 é mais leve, tem áudio Hi-Res e uma bateria que dura mais de 30 horas, ideal para viagens e foco total. Ficha Técnica: Tipo: Over-ear. Conexão: Bluetooth 5.3. Cancelamento de Ruído: Ativo (Processador QN2). Bateria: 30 horas.', '2499.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:40:25'),
(16, 'Smart TV LG OLED Evo C5 55\" 4K', 'LG', 'lg-evo.jpg', 'Eletrônicos', 'Experimente o preto perfeito e cores vibrantes com a tecnologia OLED Evo. Esta TV oferece uma imagem de cinema em casa, com 144Hz de taxa de atualização para jogos ultra-fluidos. Ficha Técnica: Tamanho: 55 polegadas. Painel: OLED Evo. Resolução: 4K UHD. Taxa de Atualização: 144Hz. Processador: Alpha 10 AI.', '6999.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:43:23'),
(17, 'Soundbar LG SC9S 3.1.3 canais Dolby Atmos', 'LG', 'soundbar.jpg', 'Eletrônicos', 'Som de cinema imersivo com Dolby Atmos e DTS:X. Esta soundbar foi projetada para se integrar perfeitamente com as TVs LG, criando uma experiência audiovisual completa. Ficha Técnica: Canais: 3.1.3. Potência: 400W. Áudio: Dolby Atmos, DTS:X. Conexão: HDMI eARC, Bluetooth.', '2199.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:45:20'),
(18, 'Caixa de Som Portátil JBL Xtreme 4', 'JBL', 'jbl-extreme.jpg', 'Eletrônicos', 'O som potente da JBL Pro Sound em um formato robusto. À prova d\'água e poeira (IP67), a Xtreme 4 tem bateria para 24 horas de festa e alça para transporte. Ficha Técnica: Potência: 80W RMS. Bateria: 24 horas. Proteção: IP67. Conexão: Bluetooth 5.3.', '1899.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:46:45'),
(19, 'Fone de Ouvido JBL Tune 770NC (Noise Cancelling)', 'JBL', 'phone-jbl.jpg', 'Eletrônicos', 'Fone over-ear leve e dobrável com cancelamento adaptativo de ruído. Mergulhe no som Pure Bass da JBL sem distrações e atenda chamadas com clareza. Ficha Técnica: Tipo: Over-ear. Cancelamento de Ruído: Adaptativo. Bateria: Até 70 horas (sem ANC). Som: JBL Pure Bass.', '499.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:50:17'),
(20, 'Console Xbox Series X', 'Microsoft', 'x-box.jpg', 'Eletrônicos', 'Console Xbox mais rápido e poderoso de todos os tempos\nJogue milhares de títulos: todos os jogos têm melhor aparência e são melhor executados no Xbox Series X\nNo coração do Series X está a Xbox Velocity Architecture, que combina um SSD personalizado e software integrado para diminuir significativamente os tempos de carregamento dentro e fora do jogo\nTroque simultaneamente entre vários jogos em um instante com o Quick Resume\nExplore novos mundos e desfrute da ação como nunca antes com 12 teraflops incomparáveis de poder de processamento gráfico\nDesfrute de jogos 4K a até 120 quadros por segundo, som 3D avançado especial e muito mais\n4K a 120 FPS: requer conteúdo e exibição compatíveis\nVersão X - com leitor de disco', '5189.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:53:09'),
(21, 'LG UltraGear Monitor Gamer 27\" OLED 240Hz 0.03ms', 'LG', 'ultra-gear.jpg', 'Eletrônicos', 'O monitor gamer definitivo para quem exige performance. O painel OLED oferece contraste infinito e um tempo de resposta quase instantâneo de 0.03ms, eliminando qualquer blur. Ficha Técnica: Tamanho: 27 polegadas. Painel: OLED. Resolução: QHD (2560x1440). Taxa de Atualização: 240Hz. Tempo de Resposta: 0.03ms (GtG).', '4500.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:54:39'),
(22, 'Notebook Gamer Avell STORM 450', 'Avell ', 'avell.jpg', 'Informática', 'Feito para quem precisa de desempenho.\n\nPrepare-se para uma revolução visual com as placas de vídeo NVIDIA RTX Série 40.\n\n\nRTX ON \nPlaca de vídeo equipada com tecnologia de ponta, como Ray Tracing em tempo real e Ray Reconstruction, além de IA avançada, essas placas oferecem um salto gigantesco em desempenho gráfico.\n\nIdeal para gamers e criadores de conteúdo que buscam o máximo em realismo e eficiência.\nDomine os jogos mais exigentes e crie conteúdos incríveis com a potência da RTX Série 40 da NVIDIA.\n\n\nO Notebook Avell Storm 450\né equipado com:\n\nGeForce® RTX 4050 \n\nNVIDIA GeForce® RTX 4050 (96 bits - 6GB GDDR6)\nNVIDIA DLSS\nRay Tracing\nVR Ready\nTGP máximo suportado: 140W\n\n', '5799.00', 1, '2025-11-13 19:37:08', '2025-11-14 18:58:24'),
(23, 'Notebook Acer Aspire 5 (Core i5 13ª Gen)', 'Acer', 'aspire-5.webp', 'Informática', 'O notebook ideal para estudos e trabalho, combinando desempenho e portabilidade. O Core i5 de 13ª geração e 16GB de RAM garantem multitarefa fluida no Windows 11. Ficha Técnica: Processador: Intel Core i5-1335U. RAM: 16GB. Armazenamento: 512GB SSD NVMe. Tela: 15.6\" Full HD IPS. Sistema: Windows 11.', '3199.00', 1, '2025-11-13 19:37:08', '2025-11-14 19:01:58'),
(24, 'Notebook Dell XPS 15 (OLED 3.5K)', 'Dell', 'dell-xps.jpg', 'Informática', 'A máquina definitiva para criadores de conteúdo. Construção premium em alumínio, tela OLED 3.5K sensível ao toque e o poder do Core Ultra 9 com uma RTX 4060 dedicada. Ficha Técnica: Processador: Intel Core Ultra 9. RAM: 32GB. Armazenamento: 2TB SSD. Placa de Vídeo: NVIDIA RTX 4060. Tela: 15.6\" OLED 3.5K Touch.', '14500.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:03:08'),
(25, 'Monitor Dell UltraSharp 27\" 4K (U2723QE)', 'Dell', 'monitor-ultrasharp.avif', 'Informática', 'O monitor padrão da indústria para produtividade e precisão de cores. Com tecnologia IPS Black para contraste superior e um hub USB-C completo com 90W de Power Delivery. Ficha Técnica: Tamanho: 27 polegadas. Resolução: 4K UHD (3840x2160). Painel: IPS Black. Conectividade: Hub USB-C (90W PD).', '3899.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:04:11'),
(26, 'Teclado Mecânico Logitech G Pro X TKL (Branco)', 'Logitech', 'teclado.jpg', 'Informática', 'O teclado TKL sem fio (Lightspeed) projetado para e-sports. Com switches GX Brown táteis, RGB Lightsync e design compacto para mais espaço para o mouse. Ficha Técnica: Formato: Tenkeyless (TKL). Conexão: Sem Fio (Lightspeed). Switches: GX Brown (Tátil). Iluminação: RGB Lightsync.', '1199.90', 1, '2025-11-13 19:37:39', '2025-11-14 19:06:19'),
(27, 'Mouse Logitech MX Master 3S - Grafite', 'Logitech', 'mx-master.jpg', 'Informática', 'O mouse ergonômico definitivo para produtividade. Rastreamento em 8K DPI que funciona até em vidro, rolagem eletromagnética MagSpeed e cliques silenciosos. Ficha Técnica: Sensor: 8K DPI (Darkfield). Rolagem: MagSpeed Eletromagnética. Botões: 7 (com cliques silenciosos). Conexão: Bluetooth / Bolt Receiver.', '549.90', 1, '2025-11-13 19:37:39', '2025-11-14 19:07:40'),
(28, 'Webcam Logitech Brio 4K', 'Logitech', 'brio.webp', 'Informática', 'Webcam profissional 4K Ultra HD para videochamadas e streaming com qualidade de imagem impecável. A tecnologia HDR e RightLight 3 ajusta a exposição em qualquer ambiente. Ficha Técnica: Resolução: 4K Ultra HD (30fps). Campo de Visão: 65°, 78°, 90° (Ajustável). Foco: Automático. Recursos: HDR, RightLight 3.', '999.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:08:30'),
(29, 'Monitor Gamer Acer Predator 27\" QHD 180Hz', 'Acer', 'predator.webp', 'Informática', 'Um monitor gamer com excelente custo-benefício. O painel Fast IPS de 27 polegadas entrega cores vibrantes, resolução QHD e 180Hz de fluidez para jogos competitivos. Ficha Técnica: Tamanho: 27 polegadas. Resolução: QHD (2560x1440). Painel: Fast IPS. Taxa de Atualização: 180Hz. Tempo de Resposta: 1ms.', '1999.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:09:15'),
(30, 'Dior Sauvage Eau de Parfum 100ml', 'Dior', 'dior-sauvage.avif', 'Perfumes', 'Uma fragrância masculina poderosa e fresca, inspirada no deserto ao pôr do sol. O Sauvage EDP combina a bergamota da Calábria com notas amadeiradas e de baunilha. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Amadeirado, Fresco. Notas Principais: Bergamota, Pimenta, Ambroxan, Baunilha.', '789.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:11:06'),
(31, 'Miss Dior Eau de Parfum 100ml', 'Dior', 'miss-dior.jpg', 'Perfumes', 'Um buquê floral aveludado que celebra o amor e a feminilidade. O novo Miss Dior é um clássico moderno, centrado na Rosa Centifolia e no Lírio-do-vale. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Floral. Notas Principais: Rosa Centifolia, Lírio-do-vale, Peônia.', '849.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:13:01'),
(32, 'Chanel Bleu de Chanel Eau de Parfum 100ml', 'Chanel', 'chanel-bleu.webp', 'Perfumes', 'Aromático amadeirado que exala elegância, profundidade e atemporalidade. O Bleu de Chanel é a escolha do homem sofisticado, com notas marcantes de sândalo e cedro. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Aromático Amadeirado. Notas Principais: Sândalo, Cedro, Fava Tonka.', '899.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:19:38'),
(33, 'Chanel Coco Mademoiselle Eau de Parfum 100ml', 'Chanel', 'chanel-coco.webp', 'Perfumes', 'Uma fragrância oriental fresca e vibrante para a mulher moderna e audaciosa. Coco Mademoiselle é um perfume de personalidade forte, com notas de laranja, jasmim e patchouli. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Oriental Fresco. Notas Principais: Laranja, Jasmim, Rosa, Patchouli.', '1150.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:21:06'),
(34, 'Paco Rabanne 1 Million Eau de Toilette 100ml', 'Paco Rabanne', 'paco-1million.jpg', 'Perfumes', 'O icônico frasco em forma de barra de ouro guarda uma fragrância amadeirada especiada que é pura sedução e poder. Um best-seller mundial. Ficha Técnica: Volume: 100ml. Concentração: Eau de Toilette (EDT). Família Olfativa: Amadeirado Especiado. Notas Principais: Menta, Canela, Couro.', '599.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:22:20'),
(35, 'Paco Rabanne Lady Million Eau de Parfum 80ml', 'Paco Rabanne', 'paco-ladymillion.jpg', 'Perfumes', 'Glamouroso e sedutor. Floral amadeirado com notas de néroli, framboesa e gardênia, em um frasco que remete a um diamante. Ficha Técnica: Volume: 80ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Floral Amadeirado. Notas Principais: Néroli, Framboesa, Gardênia.', '629.00', 1, '2025-11-13 19:37:39', '2025-11-14 19:24:43'),
(36, 'Dior J´adore Eau de Parfum 100ml', 'Dior', 'jadore-dior.jpg', 'Perfumes', 'O grande floral feminino da Dior. Bouquet icônico com Ylang-Ylang, Rosa Damascena e Jasmim Sambac, em um frasco ânfora lendário. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Floral Frutado. Notas Principais: Ylang-Ylang, Rosa Damascena, Jasmim.', '950.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:26:12'),
(37, 'Chanel N°5 Eau de Parfum 100ml', 'Chanel', 'chanel5.webp', 'Perfumes', 'O perfume lendário e atemporal. Um buquê floral abstrato com notas de aldeídos e baunilha. A própria essência da feminilidade. Ficha Técnica: Volume: 100ml. Concentração: Eau de Parfum (EDP). Família Olfativa: Floral Aldeídico. Notas Principais: Aldeídos, Jasmim, Baunilha.', '1200.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:27:35'),
(38, 'Geladeira Brastemp Frost Free Inverse 588L - Inox', 'Brastemp', 'brastemp-inverse.jpg', 'Eletrodomésticos', 'Design premium com freezer na parte inferior para melhor ergonomia. Tecnologia Inverter economiza energia e o painel touch facilita o controle. Ficha Técnica: Capacidade: 588 Litros. Tipo: Inverse (Freezer embaixo). Cor: Inox. Voltagem: 110V/220V (verificar). Tecnologia: Inverter, Frost Free.', '5899.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:29:19'),
(39, 'Micro-ondas Brastemp 32L com Grill e Painel Integrado', 'Brastemp', 'microondas-grill.webp', 'Eletrodomésticos', 'Acabamento em inox espelhado que se integra perfeitamente à sua cozinha. A função Grill permite dourar e gratinar alimentos, com diversas receitas pré-programadas. Ficha Técnica: Capacidade: 32 Litros. Cor: Inox Espelhado. Potência: 1500W. Recursos: Função Grill, Painel Integrado.', '999.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:31:47'),
(40, 'Fogão Brastemp 5 Bocas Piso com Duplo Forno - Inox', 'Brastemp', 'duplo-forno.webp', 'Eletrodomésticos', 'Permite assar duas receitas ao mesmo tempo com o forno duplo (um elétrico e um a gás). Possui acendimento superautomático e trempes de ferro fundido. Ficha Técnica: Bocas: 5. Tipo: Piso. Forno: Duplo (Elétrico + Gás). Acabamento: Inox. Acendimento: Superautomático.', '3199.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:34:44'),
(41, 'Refrigerador Electrolux Multidoor 540L (IQ8S) - Inox', 'Electrolux', 'multidoor.avif', 'Eletrodomésticos', 'Tecnologia AutoSense controla a temperatura automaticamente. A gaveta HortiNatura preserva frutas e verduras por mais tempo. Design Multidoor (French Door) com freezer Inverter. Ficha Técnica: Capacidade: 540 Litros. Tipo: Multidoor (French Door). Cor: Inox. Tecnologia: Inverter, AutoSense.', '7199.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:33:27'),
(42, 'Lava e Seca Electrolux 11kg/7kg Branca (LSP11)', 'Electrolux', 'lava-seca.avif', 'Eletrodomésticos', 'Lava 11kg e seca 7kg. A tecnologia Inverter economiza energia e o ciclo a vapor (Vapour Care) reduz rugas e elimina germes das roupas. Ficha Técnica: Capacidade: 11kg (Lavagem) / 7kg (Secagem). Cor: Branca. Tecnologia: Inverter, Vapour Care. Voltagem: 110V/220V (verificar).', '3699.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:35:58'),
(43, 'Air Fryer Electrolux by Rita Lobo 5L (EAF50)', 'Electrolux', 'air-fryer.jpg', 'Eletrodomésticos', 'Fritadeira digital desenvolvida em parceria com Rita Lobo, com 12 receitas pré-definidas. Grande capacidade de 5 litros e alta potência de 1700W. Ficha Técnica: Capacidade: 5 Litros. Cor: Grafite. Potência: 1700W. Recursos: Digital, 12 Receitas Pré-definidas.', '599.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:37:39'),
(44, 'Cervejeira Consul 82 Litros - Titanium', 'Consul', 'cervejeira.jpg', 'Eletrodomésticos', 'Mantém suas bebidas na temperatura ideal, chegando até -4°C. Capacidade para até 75 latas, com display LED e porta de vidro para fácil visualização. Ficha Técnica: Capacidade: 82 Litros (75 latas). Cor: Titanium. Temperatura: 5 níveis, até -4°C. Recursos: Display LED, Porta de Vidro.', '2100.00', 1, '2025-11-13 19:38:29', '2025-11-14 19:38:48'),
(45, 'Ar Condicionado Split Consul 12.000 BTUs Inverter', 'Consul', 'split-inverter.avif', 'Eletrodomésticos', 'Tecnologia Inverter que economiza até 77% de energia em comparação com modelos convencionais. Possui filtro HD para ar mais puro e modo silencioso. Ficha Técnica: Capacidade: 12.000 BTUs. Tipo: Split Hi-Wall. Tecnologia: Inverter. Ciclo: Frio.', '1999.99', 1, '2025-11-13 19:40:57', '2025-11-14 19:39:40'),
(46, 'Nokia 3320', 'Nokia', 'no-image.jpg', 'Celulares', 'O Nokia 3320 foi um celular de 2002, conhecido por sua extrema durabilidade, design robusto e bateria de longa duração. Lançado nos mercados dos EUA e Canadá, ele utilizava a tecnologia TDMA/AMPS (em vez de GSM), possuía tela monocromática, teclado físico, porta infravermelha para compartilhamento de contatos e jogos como \"Snake\" e \"Space Impact\". O aparelho é um ícone da simplicidade e confiabilidade, popular para colecionadores e usuários que valorizam a resistência. \nCaracterísticas principais\nDurabilidade: Extremamente resistente, conhecido como \"indestrutível\", com carcaça de plástico rígido.\nTecnologia: Utilizava a rede TDMA/AMPS, diferente do GSM comum na época.\nTela: Monocromática com tela de fundo verde.\nTeclado: Teclado físico que oferece digitação precisa e confortável.\nConectividade: Porta infravermelha para compartilhar informações como contatos e toques.\nFunções: Incluía jogos clássicos como \"Snake\" (a cobrinha) e \"Space Impact\".\nBateria: De longa duração, capaz de operar por dias com uma única carga.\nDesign: Modelo tipo \"candybar\", com botões dedicados para ligar/desligar e teclas programáveis. ', '299.95', 1, '2025-11-19 18:15:28', '2025-11-19 18:15:28');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `produtos`
--
ALTER TABLE `produtos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `produtos`
--
ALTER TABLE `produtos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
