name: CI PHP
on: [push]
jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar ferramentas
        run: composer install
      - name: Rodar Testes
        run: vendor/bin/phpunit tests/
