name: CI PHP
on: [push]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências (Composer)
        run: composer install --prefer-dist --no-progress

      - name: Rodar Testes
        run: vendor/bin/phpunit tests/
