name: CI PHP
on: [push]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências e gerar Autoload
        run: |
          composer install --prefer-dist
          composer dump-autoload

      - name: Rodar Testes
        run: vendor/bin/phpunit tests/
